app/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.add, name='add'),
    path('add_youtube/<int:id>', views.add_youtube, name='add_youtube'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('add_person/', views.add_person, name='add_person'),
    path('add_artist/', views.add_artist, name=('add_artist')),
    path('artist_songs/<int:id>/', views.artist_songs, name='artist_songs'),
]

wsd_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

app/models.py
from cgitb import text
from nturl2path import url2pathname
from statistics import mode
from turtle import title
from unicodedata import name
from django.db import models


class Person(models.Model):
    name = models.CharField('名前', max_length=32)

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField('アーティスト名', max_length=32)

    def __str__(self):
        return self.name


class Song(models.Model):
    name = models.CharField('曲名', max_length=64)
    composer = models.ForeignKey(
        Person, verbose_name='作曲者', max_length=32, on_delete=models.PROTECT, related_name='composer'
    )
    lyrist = models.ForeignKey(
        Person, verbose_name='作詞者', max_length=32, on_delete=models.PROTECT, related_name='lyrist'
    )
    artist = models.ForeignKey(
        Artist, verbose_name='アーティスト', max_length=32, on_delete=models.PROTECT, related_name='artist'
    )
#    lyrics = models.TextField('歌詞')

    def __str__(self):
        return '{0} {1} {2} {3}'.format(self.name, self.composer, self.lyrist, self.artist)


class Youtube(models.Model):
    url = models.URLField('URL')
    song = models.ForeignKey(Song, on_delete=models.PROTECT)

    def __str__(self):
        return self.url

app/forms.py
from dataclasses import fields
from pyexpat import model
from statistics import mode
from django import forms
from .models import Song, Youtube, Person, Artist


class SongCreateForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = '__all__'


class AddYoutubeForm(forms.ModelForm):

    class Meta:
        model = Youtube
        fields = ('url',)


class AddPersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = '__all__'


class AddArtistForm(forms.ModelForm):

    class Meta:
        model = Artist
        fields = '__all__'
        

app/views.py
from ast import keyword
from multiprocessing import context
from pyexpat import model
from statistics import mode
from typing_extensions import Self
from unicodedata import name
from django.shortcuts import redirect, render, get_object_or_404
from .forms import SongCreateForm, AddYoutubeForm, AddPersonForm, AddArtistForm
from .models import Song, Youtube, Person, Artist
from django.views import generic


'''
def index(request):
    context = {
        'song_list': Song.objects.all(),
    }
    return render(request, 'app/top.html', context)
'''


class IndexView(generic.ListView):
    model = Song

    def get_queryset(self):
        queryset = Song.objects.order_by('name')
        keyword = self.request.GET.get('keyword')
        if keyword:
            #icontains:キーワードが含まれている曲名を探す
            queryset = queryset.filter(name__icontains=keyword)
        return queryset


def add(request):
    form = SongCreateForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('app:index')

    context = {
        'form': SongCreateForm()
    }
    return render(request, 'app/form.html', context)


def add_youtube(request, id):
    form = AddYoutubeForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        if is_youtube_url(request.POST['url']):
            youtube = form.save(commit = False)
            youtube.song = Song.objects.get(id=id)
            youtube.save()
            return redirect('app:index')

    context = {
        'form': AddYoutubeForm(),
        'song': Song.objects.get(id=id),
#        'song_id': request.GET['song_id'],
    }
    return render(request, 'app/form.html', context)


'''引数として受け取ったURLがYoutube動画のものかチェックする関数'''
def is_youtube_url(url):
    if url[:23] == 'https://www.youtube.com':
        return True
    elif url[:16] == 'https://youtu.be':
        return True
    else:
        return False


def detail(request, id):
    song = get_object_or_404(Song, id=id)

    context = {
        'song': song,
    }
    return render(request, 'app/song_detail.html', context)


def add_person(request):
    form = AddPersonForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('app:index')

    context = {
        'form': AddPersonForm()
    }
    return render(request, 'app/form.html', context)


def add_artist(request):
    form = AddArtistForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('app:index')

    context = {
        'form': AddArtistForm()
    }
    return render(request, 'app/form.html', context)


def artist_songs(request, id):
    song = Song.objects.get(id=id)
    artist = song.artist

    context = {
        'artist': artist,
    }
    return render(request, 'app/artist_songs.html', context)

app/templates/app/artist_songs.html
{% extends 'app/base.html' %}

{% block content %}
<h1>{{ artist.name }} さんの曲</h1>
<table class="table">
    <thead>
        <tr>
            <th>曲名</th>
            <th>作曲者</th>
            <th>作詞者</th>
            <th>Youtube</th>
        </tr>
    </thead>
    <tbody>
        {% for song in artist.artist.all %}
        <tr>
            <td><a href="{% url 'app:detail' song.pk %}">{{ song.name }}</a></td>
            <td>{{ song.composer }}</td>
            <td>{{ song.lyrist }}</td>
            <td><a href="{% url 'app:add_youtube' song.pk %}">追加</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <title>Worship Song Database</title>
        <meta charset="utf-8">
    </head>
    <body>
        <header>
            <a class="top" href="{% url 'app:index' %}">Worship Song Database</a>
            <nav class="nav">
                <a class="nav-link" href="{% url 'app:add' %}">楽曲追加</a>
                <a class="nav-link" href="{% url 'app:add_person' %}">作詞作曲者追加</a>
                <a class="nav-link" href="{% url 'app:add_artist' %}">アーティスト追加</a>
                <form method="GET" action="{% url 'app:index' %}">
                    <input class="form-control" type="text" placeholder="Search" name="keyword">
                    <button type="submit">Search</button>
                </form>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

app/templates/app/form.html
{% extends 'app/base.html' %}

{% block content %}
<form action="" method="POST">
{{ form.as_p }}
<button type="submit">投稿</button>
{% csrf_token %}
</form>
{% endblock %}

app/templates/app/song_detail.html
{% extends 'app/base.html' %}

{% block content %}
<h1 id="song_name">{{song.name}}</h1>
<h2 id="composer">作曲 {{song.composer}}</h2>
<h2 id="lyrist">作詞 {{song.lyrist}}</h2>
<h2 id="youtube">Youtube</h2>
<ul id="youtube-links">
    {% for link in song.youtube_set.all %}
    <li class="youtube-link"><a href="{{ link }}">{{ link }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/app/song_form.html
{% extends 'app/base.html' %}

{% block content %}
<form action="" method="POST">
{{ form.as_p }}
<button type="submit">投稿</button>
{% csrf_token %}
</form>
{% endblock %}

app/templates/app/song_list.html
{% extends 'app/base.html' %}

{% block content %}
<h1>ワーシップソング一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>曲名</th>
            <th>作曲者</th>
            <th>作詞者</th>
            <th>アーティスト</th>
            <th>Youtube</th>
        </tr>
    </thead>
    <tbody>
        {% for song in song_list %}
        <tr>
            <td><a href="{% url 'app:detail' song.pk %}">{{ song.name }}</a></td>
            <td>{{ song.composer }}</td>
            <td>{{ song.lyrist }}</td>
            <td>{{ song.artist }}</td>
            <td><a href="{% url 'app:add_youtube' song.pk %}">追加</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/app/top.html
{% extends 'app/base.html' %}

{% block content %}
<h1>ワーシップソング一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>曲名</th>
            <th>作曲者</th>
            <th>作詞者</th>
            <th>アーティスト</th>
            <th>Youtube</th>
        </tr>
    </thead>
    <tbody>
        {% for song in song_list %}
        <tr>
            <td><a href="{% url 'app:detail' song.pk %}">{{ song.name }}</a></td>
            <td>{{ song.composer }}</td>
            <td>{{ song.lyrist }}</td>
            <td>{{ song.artist }}</td>
            <td><a href="{% url 'app:add_youtube' song.pk %}">追加</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}